/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TerminosYCondicionesRouteImport } from './routes/terminos-y-condiciones'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RegistroRouteImport } from './routes/registro'
import { Route as PoliticaDePrivacidadRouteImport } from './routes/politica-de-privacidad'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as NotificacionesRouteImport } from './routes/notificaciones'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FavoritosRouteImport } from './routes/favoritos'
import { Route as ExplorarRouteImport } from './routes/explorar'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as CategoriasRouteImport } from './routes/categorias'
import { Route as AlertasRouteImport } from './routes/alertas'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as CholloSlugRouteImport } from './routes/chollo.$slug'
import { Route as CategoriaSlugRouteImport } from './routes/categoria.$slug'
import { Route as AlertasNuevaRouteImport } from './routes/alertas_.nueva'
import { Route as AdminUsuariosRouteImport } from './routes/admin.usuarios'
import { Route as AdminTiendasRouteImport } from './routes/admin.tiendas'
import { Route as AdminChollosRouteImport } from './routes/admin.chollos'
import { Route as AdminCategoriasRouteImport } from './routes/admin.categorias'

const TerminosYCondicionesRoute = TerminosYCondicionesRouteImport.update({
  id: '/terminos-y-condiciones',
  path: '/terminos-y-condiciones',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistroRoute = RegistroRouteImport.update({
  id: '/registro',
  path: '/registro',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaDePrivacidadRoute = PoliticaDePrivacidadRouteImport.update({
  id: '/politica-de-privacidad',
  path: '/politica-de-privacidad',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificacionesRoute = NotificacionesRouteImport.update({
  id: '/notificaciones',
  path: '/notificaciones',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritosRoute = FavoritosRouteImport.update({
  id: '/favoritos',
  path: '/favoritos',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplorarRoute = ExplorarRouteImport.update({
  id: '/explorar',
  path: '/explorar',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriasRoute = CategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertasRoute = AlertasRouteImport.update({
  id: '/alertas',
  path: '/alertas',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const CholloSlugRoute = CholloSlugRouteImport.update({
  id: '/chollo/$slug',
  path: '/chollo/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriaSlugRoute = CategoriaSlugRouteImport.update({
  id: '/categoria/$slug',
  path: '/categoria/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertasNuevaRoute = AlertasNuevaRouteImport.update({
  id: '/alertas_/nueva',
  path: '/alertas/nueva',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsuariosRoute = AdminUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTiendasRoute = AdminTiendasRouteImport.update({
  id: '/tiendas',
  path: '/tiendas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminChollosRoute = AdminChollosRouteImport.update({
  id: '/chollos',
  path: '/chollos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriasRoute = AdminCategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/alertas': typeof AlertasRoute
  '/categorias': typeof CategoriasRoute
  '/contacto': typeof ContactoRoute
  '/explorar': typeof ExplorarRoute
  '/favoritos': typeof FavoritosRoute
  '/login': typeof LoginRoute
  '/notificaciones': typeof NotificacionesRoute
  '/perfil': typeof PerfilRoute
  '/politica-de-privacidad': typeof PoliticaDePrivacidadRoute
  '/registro': typeof RegistroRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terminos-y-condiciones': typeof TerminosYCondicionesRoute
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/chollos': typeof AdminChollosRoute
  '/admin/tiendas': typeof AdminTiendasRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/alertas/nueva': typeof AlertasNuevaRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/chollo/$slug': typeof CholloSlugRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alertas': typeof AlertasRoute
  '/categorias': typeof CategoriasRoute
  '/contacto': typeof ContactoRoute
  '/explorar': typeof ExplorarRoute
  '/favoritos': typeof FavoritosRoute
  '/login': typeof LoginRoute
  '/notificaciones': typeof NotificacionesRoute
  '/perfil': typeof PerfilRoute
  '/politica-de-privacidad': typeof PoliticaDePrivacidadRoute
  '/registro': typeof RegistroRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terminos-y-condiciones': typeof TerminosYCondicionesRoute
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/chollos': typeof AdminChollosRoute
  '/admin/tiendas': typeof AdminTiendasRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/alertas/nueva': typeof AlertasNuevaRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/chollo/$slug': typeof CholloSlugRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/alertas': typeof AlertasRoute
  '/categorias': typeof CategoriasRoute
  '/contacto': typeof ContactoRoute
  '/explorar': typeof ExplorarRoute
  '/favoritos': typeof FavoritosRoute
  '/login': typeof LoginRoute
  '/notificaciones': typeof NotificacionesRoute
  '/perfil': typeof PerfilRoute
  '/politica-de-privacidad': typeof PoliticaDePrivacidadRoute
  '/registro': typeof RegistroRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terminos-y-condiciones': typeof TerminosYCondicionesRoute
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/chollos': typeof AdminChollosRoute
  '/admin/tiendas': typeof AdminTiendasRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/alertas_/nueva': typeof AlertasNuevaRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/chollo/$slug': typeof CholloSlugRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/alertas'
    | '/categorias'
    | '/contacto'
    | '/explorar'
    | '/favoritos'
    | '/login'
    | '/notificaciones'
    | '/perfil'
    | '/politica-de-privacidad'
    | '/registro'
    | '/sitemap.xml'
    | '/terminos-y-condiciones'
    | '/admin/categorias'
    | '/admin/chollos'
    | '/admin/tiendas'
    | '/admin/usuarios'
    | '/alertas/nueva'
    | '/categoria/$slug'
    | '/chollo/$slug'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alertas'
    | '/categorias'
    | '/contacto'
    | '/explorar'
    | '/favoritos'
    | '/login'
    | '/notificaciones'
    | '/perfil'
    | '/politica-de-privacidad'
    | '/registro'
    | '/sitemap.xml'
    | '/terminos-y-condiciones'
    | '/admin/categorias'
    | '/admin/chollos'
    | '/admin/tiendas'
    | '/admin/usuarios'
    | '/alertas/nueva'
    | '/categoria/$slug'
    | '/chollo/$slug'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/alertas'
    | '/categorias'
    | '/contacto'
    | '/explorar'
    | '/favoritos'
    | '/login'
    | '/notificaciones'
    | '/perfil'
    | '/politica-de-privacidad'
    | '/registro'
    | '/sitemap.xml'
    | '/terminos-y-condiciones'
    | '/admin/categorias'
    | '/admin/chollos'
    | '/admin/tiendas'
    | '/admin/usuarios'
    | '/alertas_/nueva'
    | '/categoria/$slug'
    | '/chollo/$slug'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AlertasRoute: typeof AlertasRoute
  CategoriasRoute: typeof CategoriasRoute
  ContactoRoute: typeof ContactoRoute
  ExplorarRoute: typeof ExplorarRoute
  FavoritosRoute: typeof FavoritosRoute
  LoginRoute: typeof LoginRoute
  NotificacionesRoute: typeof NotificacionesRoute
  PerfilRoute: typeof PerfilRoute
  PoliticaDePrivacidadRoute: typeof PoliticaDePrivacidadRoute
  RegistroRoute: typeof RegistroRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TerminosYCondicionesRoute: typeof TerminosYCondicionesRoute
  AlertasNuevaRoute: typeof AlertasNuevaRoute
  CategoriaSlugRoute: typeof CategoriaSlugRoute
  CholloSlugRoute: typeof CholloSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terminos-y-condiciones': {
      id: '/terminos-y-condiciones'
      path: '/terminos-y-condiciones'
      fullPath: '/terminos-y-condiciones'
      preLoaderRoute: typeof TerminosYCondicionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registro': {
      id: '/registro'
      path: '/registro'
      fullPath: '/registro'
      preLoaderRoute: typeof RegistroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-de-privacidad': {
      id: '/politica-de-privacidad'
      path: '/politica-de-privacidad'
      fullPath: '/politica-de-privacidad'
      preLoaderRoute: typeof PoliticaDePrivacidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notificaciones': {
      id: '/notificaciones'
      path: '/notificaciones'
      fullPath: '/notificaciones'
      preLoaderRoute: typeof NotificacionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favoritos': {
      id: '/favoritos'
      path: '/favoritos'
      fullPath: '/favoritos'
      preLoaderRoute: typeof FavoritosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explorar': {
      id: '/explorar'
      path: '/explorar'
      fullPath: '/explorar'
      preLoaderRoute: typeof ExplorarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categorias': {
      id: '/categorias'
      path: '/categorias'
      fullPath: '/categorias'
      preLoaderRoute: typeof CategoriasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alertas': {
      id: '/alertas'
      path: '/alertas'
      fullPath: '/alertas'
      preLoaderRoute: typeof AlertasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/chollo/$slug': {
      id: '/chollo/$slug'
      path: '/chollo/$slug'
      fullPath: '/chollo/$slug'
      preLoaderRoute: typeof CholloSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categoria/$slug': {
      id: '/categoria/$slug'
      path: '/categoria/$slug'
      fullPath: '/categoria/$slug'
      preLoaderRoute: typeof CategoriaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alertas_/nueva': {
      id: '/alertas_/nueva'
      path: '/alertas/nueva'
      fullPath: '/alertas/nueva'
      preLoaderRoute: typeof AlertasNuevaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/usuarios': {
      id: '/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AdminUsuariosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tiendas': {
      id: '/admin/tiendas'
      path: '/tiendas'
      fullPath: '/admin/tiendas'
      preLoaderRoute: typeof AdminTiendasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/chollos': {
      id: '/admin/chollos'
      path: '/chollos'
      fullPath: '/admin/chollos'
      preLoaderRoute: typeof AdminChollosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categorias': {
      id: '/admin/categorias'
      path: '/categorias'
      fullPath: '/admin/categorias'
      preLoaderRoute: typeof AdminCategoriasRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminCategoriasRoute: typeof AdminCategoriasRoute
  AdminChollosRoute: typeof AdminChollosRoute
  AdminTiendasRoute: typeof AdminTiendasRoute
  AdminUsuariosRoute: typeof AdminUsuariosRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCategoriasRoute: AdminCategoriasRoute,
  AdminChollosRoute: AdminChollosRoute,
  AdminTiendasRoute: AdminTiendasRoute,
  AdminUsuariosRoute: AdminUsuariosRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AlertasRoute: AlertasRoute,
  CategoriasRoute: CategoriasRoute,
  ContactoRoute: ContactoRoute,
  ExplorarRoute: ExplorarRoute,
  FavoritosRoute: FavoritosRoute,
  LoginRoute: LoginRoute,
  NotificacionesRoute: NotificacionesRoute,
  PerfilRoute: PerfilRoute,
  PoliticaDePrivacidadRoute: PoliticaDePrivacidadRoute,
  RegistroRoute: RegistroRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TerminosYCondicionesRoute: TerminosYCondicionesRoute,
  AlertasNuevaRoute: AlertasNuevaRoute,
  CategoriaSlugRoute: CategoriaSlugRoute,
  CholloSlugRoute: CholloSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
